displayName=Music Visualizer
author=ScottyOBrien
description=Highlights nearby scenery or floor tiles to OSRS music or Windows PC audio.
tags=music,visualizer,overlay,midi,audio,tiles
plugins=com.sob.musicviz.MusicVizPlugin
build=standard
